import time
print ('Hello 1')
time.sleep(1)
print ('Hello 2')
time.sleep(1)
print ('Hello 3')
time.sleep(1)
print ('Hello 4')
time.sleep(1)
print ('Hello 5')
time.sleep(1)
print ('Hello 6')
time.sleep(1)
print ('Hello 7')
time.sleep(1)
print ('Hello 8')
time.sleep(1)
print ('Hello 9')
time.sleep(1)
print ('Hello 10')
time.sleep(1)
print ('TESTPASS')